"""initial_schema

Revision ID: ffeb3f0ec1da
Revises: 
Create Date: 2026-06-04 11:23:55.385972+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffeb3f0ec1da'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Enable pgcrypto for gen_random_uuid() (needed for UUID PKs)
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('riders',
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('preferred_language', sa.String(length=5), server_default='en', nullable=False),
    sa.Column('vehicle_type', sa.String(length=20), nullable=False),
    sa.Column('vehicle_brand_model', sa.String(length=100), nullable=True),
    sa.Column('fuel_method', sa.String(length=30), nullable=False),
    sa.Column('weekly_expense', sa.Integer(), nullable=False),
    sa.Column('monthly_maintenance', sa.Integer(), nullable=False),
    sa.Column('top_challenges', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('ev_challenges', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('petrol_challenges', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('has_accident_insurance', sa.String(length=10), nullable=False),
    sa.Column('has_health_insurance', sa.String(length=10), nullable=False),
    sa.Column('paid_out_of_pocket', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('open_to_switch', sa.String(length=20), nullable=False),
    sa.Column('switch_motivators', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('interested_in', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('referred_by_code', sa.String(length=20), nullable=True),
    sa.Column('referral_code', sa.String(length=20), nullable=False),
    sa.Column('points', sa.Integer(), server_default='10', nullable=False),
    sa.Column('referral_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('milestone_10_reached', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('milestone_25_reached', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('milestone_50_reached', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('segments', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source', sa.String(length=20), server_default='web', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('monthly_maintenance >= 0', name='ck_riders_monthly_maintenance_nonneg'),
    sa.CheckConstraint('points >= 0', name='ck_riders_points_nonneg'),
    sa.CheckConstraint('referral_count >= 0', name='ck_riders_referral_count_nonneg'),
    sa.CheckConstraint('weekly_expense >= 0', name='ck_riders_weekly_expense_nonneg'),
    sa.CheckConstraint('years_experience >= 0 AND years_experience <= 50', name='ck_riders_years_experience_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_index('idx_riders_city', 'riders', ['city'], unique=False)
    op.create_index('idx_riders_created_at', 'riders', ['created_at'], unique=False)
    op.create_index('idx_riders_phone', 'riders', ['phone'], unique=False)
    op.create_index('idx_riders_points', 'riders', ['points'], unique=False)
    op.create_index('idx_riders_referral_code', 'riders', ['referral_code'], unique=False)
    op.create_index('idx_riders_referral_count', 'riders', ['referral_count'], unique=False)
    op.create_index('idx_riders_vehicle_type', 'riders', ['vehicle_type'], unique=False)
    op.create_table('whatsapp_sessions',
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('step', sa.String(length=50), nullable=False),
    sa.Column('partial_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('language', sa.String(length=5), server_default='en', nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('phone')
    )
    op.create_table('points_transactions',
    sa.Column('rider_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('points_delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('related_rider_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_rider_id'], ['riders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pts_created_at', 'points_transactions', ['created_at'], unique=False)
    op.create_index('idx_pts_rider_id', 'points_transactions', ['rider_id'], unique=False)
    op.create_table('whatsapp_messages',
    sa.Column('rider_id', sa.UUID(), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('template', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='queued', nullable=False),
    sa.Column('twilio_sid', sa.String(length=50), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wm_phone', 'whatsapp_messages', ['phone'], unique=False)
    op.create_index('idx_wm_rider_id', 'whatsapp_messages', ['rider_id'], unique=False)
    op.create_index('idx_wm_sent_at', 'whatsapp_messages', ['sent_at'], unique=False)
    # ### end Alembic commands ###

    # ---------- Hand-written: GIN index for riders.segments -------------------
    # SQLAlchemy can't autogenerate GIN indexes for ARRAY columns. This index
    # makes ``riders.segments @> ARRAY['hot_ev_lead']`` queries fast for the
    # admin segment filters.
    op.execute("CREATE INDEX idx_riders_segments ON riders USING GIN (segments)")

    # ---------- Hand-written: trigger to auto-update updated_at --------------
    op.execute(
        "CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $rw$\n"
        "BEGIN\n"
        "  NEW.updated_at = NOW();\n"
        "  RETURN NEW;\n"
        "END;\n"
        "$rw$ LANGUAGE plpgsql"
    )
    op.execute(
        "CREATE TRIGGER trg_riders_updated_at\n"
        "BEFORE UPDATE ON riders\n"
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_wm_sent_at', table_name='whatsapp_messages')
    op.drop_index('idx_wm_rider_id', table_name='whatsapp_messages')
    op.drop_index('idx_wm_phone', table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    op.drop_index('idx_pts_rider_id', table_name='points_transactions')
    op.drop_index('idx_pts_created_at', table_name='points_transactions')
    op.drop_table('points_transactions')
    op.drop_table('whatsapp_sessions')
    op.drop_index('idx_riders_vehicle_type', table_name='riders')
    op.drop_index('idx_riders_referral_count', table_name='riders')
    op.drop_index('idx_riders_referral_code', table_name='riders')
    op.drop_index('idx_riders_points', table_name='riders')
    op.drop_index('idx_riders_phone', table_name='riders')
    op.drop_index('idx_riders_created_at', table_name='riders')
    op.drop_index('idx_riders_city', table_name='riders')
    op.drop_table('riders')
    op.drop_table('admins')
    # ### end Alembic commands ###
