"""Add pin code, platforms, follow up flag

Revision ID: 232fb1d552e6
Revises: ffeb3f0ec1da
Create Date: 2026-06-08 12:18:18.456841+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '232fb1d552e6'
down_revision: str | Sequence[str] | None = 'ffeb3f0ec1da'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riders', sa.Column('pin_code', sa.String(length=10), server_default='000000', nullable=False))
    op.add_column('riders', sa.Column('platforms', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False))
    op.add_column('riders', sa.Column('follow_up_flag', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('riders', 'follow_up_flag')
    op.drop_column('riders', 'platforms')
    op.drop_column('riders', 'pin_code')
    # ### end Alembic commands ###
