"""add telegram_chat_id to riders

Revision ID: 84e1470ba6d6
Revises: 232fb1d552e6
Create Date: 2026-06-09 18:43:49.083644+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e1470ba6d6'
down_revision: str | Sequence[str] | None = '232fb1d552e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riders', sa.Column('telegram_chat_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_riders_telegram_chat_id', 'riders', ['telegram_chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_riders_telegram_chat_id', 'riders', type_='unique')
    op.drop_column('riders', 'telegram_chat_id')
    # ### end Alembic commands ###
